[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "cookiecutter-pypackage"
version = "0.3.1"
description = "🐍🍪 Another Python Cookiecutter"
readme = "README.md"
authors = ["billsioros <billsioros97@gmail.com>"]
license = "MIT"
homepage = "https://billsioros.github.io/cookiecutter-pypackage"
repository = "https://github.com/billsioros/cookiecutter-pypackage"
keywords = []
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/billsioros/cookiecutter-pypackage/issues"
"Changelog" = "https://github.com/billsioros/cookiecutter-pypackage/releases"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
python-semantic-release = "^7.15.3"
flake8 = "^3.9.2"
flakehell = "^0.9.0"
wemake-python-styleguide = "^0.15.2"
isort = "^5.9.3"
black = "^20.8b1"
pre-commit = "^2.12.1"
poethepoet = "^0.10.0"
pytest = "^6.2.4"
pytest-sugar = "^0.9.4"
pytest-clarity = "^1.0.1"
tox = "^3.23.0"
tox-poetry-installer = { extras = ["poetry"], version = "^0.8.0" }
tox-gh-actions = "^2.5.0"
tox-pyenv = "^1.1.0"
mkdocs = "^1.1.2"
mkdocs-material = "^7.1.3"
mkdocs-minify-plugin = "^0.4.0"
mkdocs-redirects = "^1.0.3"
mkdocstrings = "^0.15.0"
mdx-truly-sane-lists = "^1.2"
mike = "^1.0.1"
pytest-cookies = "^0.6.1"

[tool.semantic_release]
upload_to_pypi = false
version_toml = "pyproject.toml:tool.poetry.version"
changelog_components = "semantic_release.changelog.changelog_headers,semantic_release.changelog.compare_url"
build_command = false

[tool.vulture]
min_confidence = 95
paths = ["cookiecutter-pypackage", "hooks", "tests"]

[tool.poe.tasks]
clean = { cmd = "rm -rf ./**/__pycache__ dist site .pytest_cache", help = "Clean up any auxiliary files" }
format = { shell = "poetry run isort .; poetry run black .", help = "Format your codebase" }
hooks = { cmd = "poetry run pre-commit run --all-files", help = "Run all pre-commit hooks" }
test = { cmd = "poetry run pytest --cov=cookiecutter-pypackage", help = "Run the test suite" }
lint = { cmd = "poetry run flakehell lint", help = "Lint your code for errors" }
docs = { shell = "python -c 'import webbrowser; webbrowser.open(\"http://127.0.0.1:8000\")'; poetry run mkdocs serve", help = "Build and serve the documentation" }

[tool.pytest.ini_options]
addopts = "-vv --color=yes"
log_cli = false
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_level = "INFO"
python_files = "test_*.py"
python_functions = "test_*"
testpaths = "tests"

[tool.isort]
profile = "black"
src_paths = ["cookiecutter-pypackage", "hooks", "tests"]
line_length = 99

[tool.black]
line-length = 99
target-version = ["py37", "py38"]
skip-string-normalization = true
exclude = "{{cookiecutter.project_name}}"

[tool.flakehell]
exclude = [
  ".git",
  ".github",
  ".pytest_cache",
  ".tox",
  ".vscode",
  ".venv",
  "docs",
  "__pycache__",
  "README.md",
  "{{cookiecutter.project_name}}"
]
format = "colored"
show_source = false
statistics = false
docstring-convention = "google"

accept_encodings = "utf-8"
max_line_length = 99

extended_default_ignore = []

[tool.flakehell.plugins]
"flake8-*" = ["+*"]
mccabe = ["+*"]
nitpick = ["+*"]
"pep8-naming" = ["+*"]
pycodestyle = ["+*"]
pyflakes = ["+*"]
"wemake-python-styleguide" = ["+*"]
