[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core>=1",
]

[tool.poetry]
name = "cookiecutter-pypackage"
version = "1.5.4"
description = "🐍🍪 Another Python Cookiecutter"
license = "MIT"
authors = [ "billsioros <billsioros97@gmail.com>" ]
readme = "README.md"
homepage = "https://billsioros.github.io/cookiecutter-pypackage"
repository = "https://github.com/billsioros/cookiecutter-pypackage"
keywords = []
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
]
dependencies.python = "^3.9"
group.dev.dependencies.black = "*"
group.dev.dependencies.isort = "*"
group.dev.dependencies.mdx-truly-sane-lists = "*"
group.dev.dependencies.mike = "*"
group.dev.dependencies.mkdocs = "*"
group.dev.dependencies.mkdocs-material = "*"
group.dev.dependencies.mkdocs-minify-plugin = "*"
group.dev.dependencies.mkdocs-redirects = "*"
group.dev.dependencies.poethepoet = "*"
group.dev.dependencies.pre-commit = "*"
group.dev.dependencies.pytest = "*"
group.dev.dependencies.pytest-clarity = "*"
group.dev.dependencies.pytest-cookies = "*"
group.dev.dependencies.pytest-sugar = "*"
group.dev.dependencies.python-semantic-release = "10.6.2"
urls."Bug Tracker" = "https://github.com/billsioros/cookiecutter-pypackage/issues"
urls.Changelog = "https://github.com/billsioros/cookiecutter-pypackage/releases"

[tool.black]
target-version = [ "py37", "py38" ]
line-length = 99
exclude = "{{cookiecutter.project_name}}"
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 99
src_paths = [ "cookiecutter-pypackage", "hooks", "tests" ]

[tool.docformatter]
in-place = true
recursive = true
black = true
non-strict = true
non-cap = [
  "cookiecutter-pypackage",
]

[tool.bandit]
exclude_dirs = [ "tests" ]
recursive = true

[tool.pytest]
ini_options.testpaths = "tests"
ini_options.python_files = "test_*.py"
ini_options.python_functions = "test_*"
ini_options.addopts = "-vv --color=yes"
ini_options.log_cli = false
ini_options.log_cli_level = "INFO"
ini_options.log_cli_format = "%(asctime)s %(levelname)s %(message)s"
ini_options.log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
build_command = false
changelog_components = "semantic_release.changelog.changelog_headers,semantic_release.changelog.compare_url"
upload_to_pypi = false

[tool.poe]
tasks.clean = { cmd = "rm -rf ./**/__pycache__ dist site .pytest_cache", help = "Clean up any auxiliary files" }
tasks.format = { shell = "poetry run isort .; poetry run black .", help = "Format your codebase" }
tasks.hooks = { cmd = "poetry run pre-commit run --all-files", help = "Run all pre-commit hooks" }
tasks.test = { cmd = "poetry run pytest --cov=cookiecutter-pypackage", help = "Run the test suite" }
tasks.lint = { cmd = "poetry run ruff check src", help = "Lint your code for errors" }
tasks.docs = { shell = "python -c 'import webbrowser; webbrowser.open(\"http://127.0.0.1:8000\")'; poetry run mkdocs serve", help = "Build and serve the documentation" }
tasks.export = { cmd = "poetry export --without-hashes --dev -o requirements.txt" }
