name: 🐞 Bug Report
description: Did you find a bug?
title: "🐞 "
labels: [":bug: bug"]
assignees:
  - billsioros
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Describe the problem!
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: How can we reproduce the bug?
      description: Please provide the reproduction steps corresponding to the bug.
      placeholder: Provide us with some python code!
    validations:
      required: true
  - type: textarea
    id: stack-trace
    attributes:
      label: Relevant stack trace
      description: Please provide us with the program's stack trace, if appropriate.
      render: shell
  - type: checkboxes
    id: duplicate-issue
    attributes:
      label: Is this a duplicate issue?
      description: By submitting this issue, you confirm that you have made sure that this is not a duplicate issue
      options:
        - label: I confirm that this is not a duplicate issue
          required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://Group4Life.github.io/cookiecutter-pypackage/latest/CODE_OF_CONDUCT/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
