blank_issues_enabled: false
contact_links:
  - name: Q&A
    url: https://github.com/{{cookiecutter.github_user}}/{{cookiecutter.project_name}}/discussions/categories/q-a
    about: Please ask and answer questions here.
