name: CI
on:
  push:
    branches: [master]
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
jobs:
  test:
    runs-on: ${{ '{{' }} matrix.platform {{ '}}' }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.2.2
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
          path: .venv
          key: venv-${{ '{{' }} runner.os {{ '}}' }}-${{ '{{' }} matrix.platform {{ '}}' }}-${{ '{{' }} matrix.python-version {{ '}}' }}-${{ '{{' }} hashFiles('**/poetry.lock') {{ '}}' }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Run the test suite
        run: poetry run pytest
