name: CI

on:
  push:
    branches: [master]
    paths:
      - '{{cookiecutter.project_name}}/**/*.py'
      - 'tests/**/*.py'
      - 'examples/**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches: [master]
    paths:
      - '{{cookiecutter.project_name}}/**/*.py'
      - 'tests/**/*.py'
      - 'examples/**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  tox:
    runs-on: ${{ '{{' }} matrix.platform {{ '}}' }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ '{{' }} matrix.python-version {{ '}}' }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ '{{' }} matrix.python-version {{ '}}' }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.2
        with:
          poetry-version: 1.1.6

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            .tox
            .venv
          key: ${{ '{{' }} matrix.platform {{ '}}' }}-tox-venv-${{ '{{' }} matrix.python-version {{ '}}' }}-${{ '{{' }} hashFiles('**/poetry.lock') {{ '}}' }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Test with tox
        run: poetry run python -m tox
