name: Greetings
on: [issues]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ '{{' }} secrets.GITHUB_TOKEN {{ '}}' }}
          issue-message: "Thank you for contributing to **{{cookiecutter.project_name}}**! Please remember to reference our [Contributing Guidelines]({{ cookiecutter.github_repository }}/blob/master/docs/CONTRIBUTING.md)."
          pr-message: "Thank you for contributing to **{{cookiecutter.project_name}}**! Please remember to reference our [Contributing Guidelines]({{ cookiecutter.github_repository }}/blob/master/docs/CONTRIBUTING.md)."
