name: Misspell

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: sobolevn/misspell-fixer-action@0.1.0
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: correct typos `[misspell-fixer]`'
        title: 'Fixing typos (misspell-fixer)'
