name: Preview Docs
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'docs/**'
      - '*.md'
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.2.2
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
          path: .venv
          key: venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          poetry install
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: site
          teardown: 'true'
          build: |
            poetry run mkdocs build
