name: Sync

on:
  workflow_run:
    workflows: ["CD"]
    types:
      - completed

jobs:
  merge:
    name: Merge master -> development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: development
          github_token: ${{ secrets.GITHUB_TOKEN }}
